### ISSUE TITLE
KeyError: 'auth-info-required' when opening credentials dialog in Ubuntu 19.10

### ISSUE THREAD

**Issue by johannes-riecken** [OpenPrinting/system-config-printer#163]
We use secure printing with a Canon ImageRunner ADVANCE C5550/5560. When starting a print job on Ubuntu 19.10 the "Credentials required" toaster pops up, but clicking on it does not show the credentials dialog. Instead the following back-trace shows up in the command line:

```
(system-config-printer:28275): GLib-GIO-CRITICAL **: 17:23:51.439: g_dbus_connection_call_internal: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(system-config-printer:28275): GLib-GIO-CRITICAL **: 17:23:51.441: g_dbus_connection_call_internal: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
Traceback (most recent call last):
  File "/usr/share/system-config-printer/jobviewer.py", line 1621, in on_job_authenticate_activate
    uri, auth_info_required, True)
  File "/usr/share/system-config-printer/jobviewer.py", line 1111, in get_authentication
    self.display_auth_info_dialog (job, keyring_attrs)
  File "/usr/share/system-config-printer/jobviewer.py", line 1115, in display_auth_info_dialog
    auth_info_required = data['auth-info-required']
KeyError: 'auth-info-required'
^CTraceback (most recent call last):
  File "/usr/share/system-config-printer/system-config-printer.py", line 2264, in <module>
    main(show_jobs)
  File "/usr/share/system-config-printer/system-config-printer.py", line 2238, in main
    Gtk.main()
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 1630, in main
    return _Gtk_main(*args, **kwargs)
  File "/usr/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/usr/lib/python3/dist-packages/gi/_ossighelper.py", line 251, in register_sigint_fallback
    signal.default_int_handler(signal.SIGINT, None)
KeyboardInterrupt
```

**Comment by zdohnal** [comment]
Hi @johannes-riecken ,

this traceback is solved in #143 , please report the issue to Ubuntu.
