### ISSUE TITLE
 scp-dbus-service.py crashed with SIGSEGV 

### ISSUE THREAD

**Issue by Esokrates** [OpenPrinting/system-config-printer#181]
Disclaimer: I reported this downstream at the ubuntu launchpad tracker (https://bugs.launchpad.net/ubuntu/+source/system-config-printer/+bug/1896622), but I noticed there it not much happening there, so maybe here it might be a better place before this info gets lost.

```
Package: system-config-printer-common 1.5.12-0ubuntu1
```

The following crash happened to me in an Ubuntu 20.04 session, fully updated (this is an excerpt of the apport crash file I ran through apport-retrace):
```
SegvAnalysis:
 Segfault happened at: 0x506bd7:	mov    %rcx,(%rdx)
 PC (0x00506bd7) ok
 source "%rcx" ok
 destination "(%rdx)" (0x00000004) not located in a known VMA region (needed writable region)!
 Stack memory exhausted (SP below stack segment)
SegvReason: writing NULL VMA
Signal: 11
SourcePackage: system-config-printer
Stacktrace:
 #0  0x0000000000506bd7 in  ()
 #1  0x00007fde3b6819f5 in _Py_DECREF (filename=<synthetic pointer>, lineno=541, op=<optimized out>) at /usr/include/python3.8/object.h:478
         tls = 0x7fde30002ad0
 #2  _Py_XDECREF (op=<optimized out>) at /usr/include/python3.8/object.h:541
         tls = 0x7fde30002ad0
 #3  destroy_TLS (value=0x7fde30002ad0) at cupsmodule.c:67
         tls = 0x7fde30002ad0
 #4  0x00007fde4c4795a1 in __nptl_deallocate_tsd () at pthread_create.c:301
         data = <optimized out>
         level2 = 0x7fde3a3aba10
         idx = <optimized out>
         cnt = 0
 #5  0x00007fde4c47a62a in __nptl_deallocate_tsd () at pthread_create.c:256
         pd = <optimized out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140592436393728, -3499183623227771153, 140724867734478, 140724867734479, 140724867734624, 140592436391872, 3516206840480593647, 3516466368495417071}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
         not_first_call = 1
 #6  start_thread (arg=<optimized out>) at pthread_create.c:488
         pd = <optimized out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140592436393728, -3499183623227771153, 140724867734478, 140724867734479, 140724867734624, 140592436391872, 3516206840480593647, 3516466368495417071}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
         not_first_call = 1
 #7  0x00007fde4c5b6103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
StacktraceAddressSignature: /usr/share/system-config-printer/scp-dbus-service.py:11:/usr/bin/python3.8+e3bd7:/usr/lib/python3/dist-packages/cups.cpython-38-x86_64-linux-gnu.so+19f5:/usr/lib/x86_64-linux-gnu/libpthread-2.31.so+15a1:/usr/lib/x86_64-linux-gnu/libpthread-2.31.so+262a:/usr/lib/x86_64-linux-gnu/libc-2.31.so+fd103
StacktraceSource:
 #0  0x0000000000506bd7 in  ()
 #1  0x00007fde3b6819f5 in _Py_DECREF (filename=<synthetic pointer>, lineno=541, op=<optimized out>) at /usr/include/python3.8/object.h:478
   [Error: object.h was not found in source tree]
 #2  _Py_XDECREF (op=<optimized out>) at /usr/include/python3.8/object.h:541
   [Error: object.h was not found in source tree]
 #3  destroy_TLS (value=0x7fde30002ad0) at cupsmodule.c:67
   [Error: cupsmodule.c was not found in source tree]
 #4  0x00007fde4c4795a1 in __nptl_deallocate_tsd () at pthread_create.c:301
   [Error: pthread_create.c was not found in source tree]
 #5  0x00007fde4c47a62a in __nptl_deallocate_tsd () at pthread_create.c:256
   [Error: pthread_create.c was not found in source tree]
 #6  start_thread (arg=<optimized out>) at pthread_create.c:488
   [Error: pthread_create.c was not found in source tree]
 #7  0x00007fde4c5b6103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
   [Error: clone.S was not found in source tree]
 
StacktraceTop:
 ()
 _Py_DECREF (filename=<synthetic pointer>, lineno=541, op=<optimized out>) at /usr/include/python3.8/object.h:478
 _Py_XDECREF (op=<optimized out>) at /usr/include/python3.8/object.h:541
 destroy_TLS (value=0x7fde30002ad0) at cupsmodule.c:67
 __nptl_deallocate_tsd () at pthread_create.c:301
Tags: focal wayland-session
ThreadStacktrace:
 .
 Thread 5 (Thread 0x7fde489b8700 (LWP 55391)):
 warning: Unexpected size of section `.reg-xstate/55391' in core file.
 #0  0x00007fde4c5a996f in __GI___poll (fds=0x233d3a0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
         resultvar = 18446744073709551100
         sc_cancel_oldtype = 0
 #1  0x00007fde4b8c21ae in g_main_context_poll (priority=<optimized out>, n_fds=1, fds=0x233d3a0, timeout=<optimized out>, context=0x233d500) at ../../../glib/gmain.c:4346
         ret = <optimized out>
         errsv = <optimized out>
         poll_func = 0x7fde4b8d1f10 <g_poll>
         max_priority = 2147483647
         timeout = -1
         some_ready = <optimized out>
         nfds = 1
         allocated_nfds = <optimized out>
         fds = 0x233d3a0
 #2  g_main_context_iterate (context=context@entry=0x233d500, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../glib/gmain.c:4042
         max_priority = 2147483647
         timeout = -1
         some_ready = <optimized out>
         nfds = 1
         allocated_nfds = <optimized out>
         fds = 0x233d3a0
 #3  0x00007fde4b8c22e3 in g_main_context_iteration (context=0x233d500, may_block=1) at ../../../glib/gmain.c:4108
         retval = <optimized out>
 #4  0x00007fde4a53699d in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
 #5  0x00007fde4b8eb931 in g_thread_proxy (data=0x2341120) at ../../../glib/gthread.c:807
         thread = 0x2341120
         __func__ = "g_thread_proxy"
 #6  0x00007fde4c47a609 in start_thread (arg=<optimized out>) at pthread_create.c:477
         ret = <optimized out>
         pd = <optimized out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140592677619456, -3499183623227771153, 140724867727342, 140724867727343, 140724867727488, 140592677617600, 3516456156352804591, 3516466368495417071}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
         not_first_call = 0
 #7  0x00007fde4c5b6103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
 .
 Thread 4 (Thread 0x7fde491c4700 (LWP 55390)):
 warning: Unexpected size of section `.reg-xstate/55390' in core file.
 #0  0x00007fde4c5a996f in __GI___poll (fds=0x7fde3c0101e0, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
         resultvar = 18446744073709551100
         sc_cancel_oldtype = 0
 #1  0x00007fde4b8c21ae in g_main_context_poll (priority=<optimized out>, n_fds=2, fds=0x7fde3c0101e0, timeout=<optimized out>, context=0x7fde3c00e220) at ../../../glib/gmain.c:4346
         ret = <optimized out>
         errsv = <optimized out>
         poll_func = 0x7fde4b8d1f10 <g_poll>
         max_priority = 2147483647
         timeout = -1
         some_ready = <optimized out>
         nfds = 2
         allocated_nfds = <optimized out>
         fds = 0x7fde3c0101e0
 #2  g_main_context_iterate (context=0x7fde3c00e220, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../glib/gmain.c:4042
         max_priority = 2147483647
         timeout = -1
         some_ready = <optimized out>
         nfds = 2
         allocated_nfds = <optimized out>
         fds = 0x7fde3c0101e0
 #3  0x00007fde4b8c2533 in g_main_loop_run (loop=0x7fde3c00e310) at ../../../glib/gmain.c:4241
         __func__ = "g_main_loop_run"
 #4  0x00007fde4b702eda in gdbus_shared_thread_func (user_data=0x7fde3c00e1f0) at ../../../gio/gdbusprivate.c:279
         data = 0x7fde3c00e1f0
 #5  0x00007fde4b8eb931 in g_thread_proxy (data=0x7fde3c002000) at ../../../glib/gthread.c:807
         thread = 0x7fde3c002000
         __func__ = "g_thread_proxy"
 #6  0x00007fde4c47a609 in start_thread (arg=<optimized out>) at pthread_create.c:477
         ret = <optimized out>
         pd = <optimized out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140592686057216, -3499183623227771153, 140592694615182, 140592694615183, 140592694615328, 140592686055360, 3516454998859118319, 3516466368495417071}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
         not_first_call = 0
 #7  0x00007fde4c5b6103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
 .
 Thread 3 (Thread 0x7fde4c2c8740 (LWP 55387)):
 warning: Unexpected size of section `.reg-xstate/55387' in core file.
 #0  0x00000000004ec3ca in  ()
 #1  0x000000000066babb in _PyGC_CollectNoFail ()
 #2  0x000000000067dd60 in PyImport_Cleanup ()
 #3  0x0000000000678450 in Py_FinalizeEx ()
 #4  0x00000000006aeab9 in Py_RunMain ()
 #5  0x00000000006aed29 in Py_BytesMain ()
 #6  0x00007fde4c4bb0b3 in __libc_start_main (main=0x4ebd20 <main>, argc=2, argv=0x7ffd0fc0b388, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd0fc0b378) at ../csu/libc-start.c:308
         result = <optimized out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {7007552, -3499183623227771153, 6251200, 140724867740544, 0, 0, 3497740594051348207, 3516466471149172463}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x2, 0x7ffd0fc0b388}, data = {prev = 0x0, cleanup = 0x0, canceltype = 2}}}
         not_first_call = <optimized out>
 #7  0x00000000005f62ee in _start ()
 .
 Thread 2 (Thread 0x7fde4a1ef700 (LWP 55388)):
 warning: Unexpected size of section `.reg-xstate/55388' in core file.
 #0  0x00007fde4c5a996f in __GI___poll (fds=0x2329d90, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
         resultvar = 18446744073709551100
         sc_cancel_oldtype = 0
 #1  0x00007fde4b8c21ae in g_main_context_poll (priority=<optimized out>, n_fds=1, fds=0x2329d90, timeout=<optimized out>, context=0x232d010) at ../../../glib/gmain.c:4346
         ret = <optimized out>
         errsv = <optimized out>
         poll_func = 0x7fde4b8d1f10 <g_poll>
         max_priority = 2147483647
         timeout = -1
         some_ready = <optimized out>
         nfds = 1
         allocated_nfds = <optimized out>
         fds = 0x2329d90
 #2  g_main_context_iterate (context=context@entry=0x232d010, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../glib/gmain.c:4042
         max_priority = 2147483647
         timeout = -1
         some_ready = <optimized out>
         nfds = 1
         allocated_nfds = <optimized out>
         fds = 0x2329d90
 #3  0x00007fde4b8c22e3 in g_main_context_iteration (context=0x232d010, may_block=may_block@entry=1) at ../../../glib/gmain.c:4108
         retval = <optimized out>
 #4  0x00007fde4b8c2331 in glib_worker_main (data=<optimized out>) at ../../../glib/gmain.c:5996
 #5  0x00007fde4b8eb931 in g_thread_proxy (data=0x231a6a0) at ../../../glib/gthread.c:807
         thread = 0x231a6a0
         __func__ = "g_thread_proxy"
 #6  0x00007fde4c47a609 in start_thread (arg=<optimized out>) at pthread_create.c:477
         ret = <optimized out>
         pd = <optimized out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140592703010560, -3499183623227771153, 140724867727838, 140724867727839, 140724867727984, 140592703008704, 3516452819700086511, 3516466368495417071}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
         not_first_call = 0
 #7  0x00007fde4c5b6103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
 .
 Thread 1 (Thread 0x7fde3a3ab700 (LWP 55392)):
 #0  0x0000000000506bd7 in  ()
 #1  0x00007fde3b6819f5 in _Py_DECREF (filename=<synthetic pointer>, lineno=541, op=<optimized out>) at /usr/include/python3.8/object.h:478
         tls = 0x7fde30002ad0
 #2  _Py_XDECREF (op=<optimized out>) at /usr/include/python3.8/object.h:541
         tls = 0x7fde30002ad0
 #3  destroy_TLS (value=0x7fde30002ad0) at cupsmodule.c:67
         tls = 0x7fde30002ad0
 #4  0x00007fde4c4795a1 in __nptl_deallocate_tsd () at pthread_create.c:301
         data = <optimized out>
         level2 = 0x7fde3a3aba10
         idx = <optimized out>
         cnt = 0
 #5  0x00007fde4c47a62a in __nptl_deallocate_tsd () at pthread_create.c:256
         pd = <optimized out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140592436393728, -3499183623227771153, 140724867734478, 140724867734479, 140724867734624, 140592436391872, 3516206840480593647, 3516466368495417071}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
         not_first_call = 1
 #6  start_thread (arg=<optimized out>) at pthread_create.c:488
         pd = <optimized out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140592436393728, -3499183623227771153, 140724867734478, 140724867734479, 140724867734624, 140592436391872, 3516206840480593647, 3516466368495417071}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
         not_first_call = 1
 #7  0x00007fde4c5b6103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

I can't tell for sure what triggered the crash, but my printer was not responding to jobs around that time so I cancelled and resent the job multiple times in a row.

**Comment by Esokrates** [comment]
Oh I just noticed https://github.com/OpenPrinting/system-config-printer/issues/176 so I guess this is a duplicate?

**Comment by zdohnal** [comment]
Yep, it is a duplicate, closing.
