### ISSUE TITLE
"ValueError: Namespace Notify not available for version 0.7" with libnotify 0.7

### ISSUE THREAD

**Issue by rffontenelle** [OpenPrinting/system-config-printer#276]
Having libnotify updated from 0.7 to 0.8, I get the traceback below. It seems [jobviewer.py line 29](https://github.com/OpenPrinting/system-config-printer/blob/e5a6b3c0107969d698c17560ea4854c85b153336/jobviewer.py#L29) and [applet.py line 52](https://github.com/OpenPrinting/system-config-printer/blob/2c09ddfb25713e38f7a9810193339c7c65c5f2ea/applet.py#L52) require Notify 0.7

```
$ system-config-printer
Traceback (most recent call last):
  File "/usr/share/system-config-printer/system-config-printer.py", line 84, in <module>
    import jobviewer
  File "/usr/share/system-config-printer/jobviewer.py", line 29, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Notify not available for version 0.7
```

Environment: Arch Linux, system-config-printer 1.5.16, libnotify 0.8

**Comment by thbemme** [comment]
Same error here for cinnamon-settings
```
$ cinnamon-settings
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 793, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 317, in __init__
    self.init_settings_overview()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 325, in init_settings_overview
    self.load_python_modules()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 494, in load_python_modules
    for module in map(__import__, to_import):
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_notifications.py", line 4, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Notify not available for version 0.7

$ pamac list -i |grep -E "libnotify|cinnamon-settings"
cinnamon-settings-daemon           5.4.1-1                       community  2.0 MB
libnotify                          0.8.0-1                       extra      329.0 kB
```

**Comment by robin0800** [comment]
"gi.require_version('Notify', '0.7')"  This requires to read "gi.require_version('Notify', '0.8')" to work

**Comment by heftig** [comment]
The Arch Linux `libnotify` package patched the module version back to `0.7`, see https://gitlab.gnome.org/GNOME/libnotify/-/issues/27.

**Comment by heftig** [comment]
[libnotify 0.8.1](https://gitlab.gnome.org/GNOME/libnotify/-/tags/0.8.1) should fix this.

**Comment by rffontenelle** [comment]
Thanks for the info updates. Closing this then
